In [3]:
import matplotlib
import numpy as np

In [4]:
import numpy as np

data = """0100
0010
0110
1111
0110
1110
0110
1010
0110
1111
0111
0101
0111
0010
0010
0000
0110
1100
0110
0101
0010
0000
0110
1101
0110
1111
0110
1110
0110
0100
0110
0101
0010
0001"""

# Split the string into rows
rows = data.split('\n')

# Convert each row to a list of integers
matrix = [list(map(int, list(row))) for row in rows]

# Convert the list of lists to a 2D numpy array
numpy_array = np.array(matrix)

# Print the result
print(numpy_array)

[0 0 1 0]


In [7]:

# Define two matrices
matrix_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_b = np.array([[1, 0, 0], [0, 0, 1], [0, 1, 0]])

# Perform matrix multiplication
result = np.matmul(matrix_a, matrix_b)
# Alternatively: result = matrix_a @ matrix_b

print("Matrix A:")
print(matrix_a)

print("\nMatrix B:")
print(matrix_b)

print("\nResult of Matrix Multiplication:")
print(result)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[1 0 0]
 [0 0 1]
 [0 1 0]]

Result of Matrix Multiplication:
[[1 3 2]
 [4 6 5]
 [7 9 8]]


In [9]:
matrix_permutation = np.array([[0, 1, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [1, 0, 0, 0]])
result = np.matmul(numpy_array, matrix_permutation)
print(result)


[[0 0 0 1]
 [0 0 1 0]
 [0 0 1 1]
 [1 1 1 1]
 [0 0 1 1]
 [0 1 1 1]
 [0 0 1 1]
 [0 1 1 0]
 [0 0 1 1]
 [1 1 1 1]
 [1 0 1 1]
 [1 0 0 1]
 [1 0 1 1]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 1 1]
 [0 1 0 1]
 [0 0 1 1]
 [1 0 0 1]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 1 1]
 [1 1 0 1]
 [0 0 1 1]
 [1 1 1 1]
 [0 0 1 1]
 [0 1 1 1]
 [0 0 1 1]
 [0 0 0 1]
 [0 0 1 1]
 [1 0 0 1]
 [0 0 1 0]
 [1 0 0 0]]


In [11]:
flattened_array = result.flatten()
print(flattened_array)



[0 0 0 1 0 0 1 0 0 0 1 1 1 1 1 1 0 0 1 1 0 1 1 1 0 0 1 1 0 1 1 0 0 0 1 1 1
 1 1 1 1 0 1 1 1 0 0 1 1 0 1 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 1 0 1 0 1 0 0
 1 1 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 1 1 0 1 0 0 1 1 1 1 1 1 0 0 1 1 0 1 1
 1 0 0 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 0 1 0 1 0 0 0]


In [12]:
original_string = "1000001010101111101010111010001110101111111011001110001000100000101010011010110000100000101011011010111110101011101010001010110000100100"

# Insert spaces every 4 characters
spaced_string = ' '.join([original_string[i:i+4] for i in range(0, len(original_string), 4)])

print(spaced_string)

1000 0010 1010 1111 1010 1011 1010 0011 1010 1111 1110 1100 1110 0010 0010 0000 1010 1001 1010 1100 0010 0000 1010 1101 1010 1111 1010 1011 1010 1000 1010 1100 0010 0100
