In [3]:
import matplotlib
import numpy as np

In [13]:
import numpy as np

data = """0100
0010
0110
1111
0110
1110
0110
1010
0110
1111
0111
0101
0111
0010
0010
0000
0110
1100
0110
0101
0010
0000
0110
1101
0110
1111
0110
1110
0110
0100
0110
0101
0010
0001"""

# Split the string into rows
rows = data.split('\n')

# Convert each row to a list of integers
matrix = [list(map(int, list(row))) for row in rows]

# Convert the list of lists to a 2D numpy array
numpy_array = np.array(matrix)

# Print the result
print(numpy_array)

[[0 1 0 0]
 [0 0 1 0]
 [0 1 1 0]
 [1 1 1 1]
 [0 1 1 0]
 [1 1 1 0]
 [0 1 1 0]
 [1 0 1 0]
 [0 1 1 0]
 [1 1 1 1]
 [0 1 1 1]
 [0 1 0 1]
 [0 1 1 1]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 0 0]
 [0 1 1 0]
 [1 1 0 0]
 [0 1 1 0]
 [0 1 0 1]
 [0 0 1 0]
 [0 0 0 0]
 [0 1 1 0]
 [1 1 0 1]
 [0 1 1 0]
 [1 1 1 1]
 [0 1 1 0]
 [1 1 1 0]
 [0 1 1 0]
 [0 1 0 0]
 [0 1 1 0]
 [0 1 0 1]
 [0 0 1 0]
 [0 0 0 1]]


In [23]:
matrix_test = np.array([[0, 1, 0, 0], [0, 0, 1, 0], [0, 1, 1, 0]])
matrix_permutation = np.array([[0, 1, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [1, 0, 0, 0]])

# Transpose matrix_permutation before multiplication
result = np.matmul(matrix_test, matrix_permutation.T)
# Alternatively: result = matrix_test @ matrix_permutation.T

print(result)




[[1 0 0 0]
 [0 0 1 0]
 [1 0 1 0]]


In [24]:
result = np.matmul(numpy_array, matrix_permutation.T)

print(result)

[[1 0 0 0]
 [0 0 1 0]
 [1 0 1 0]
 [1 1 1 1]
 [1 0 1 0]
 [1 0 1 1]
 [1 0 1 0]
 [0 0 1 1]
 [1 0 1 0]
 [1 1 1 1]
 [1 1 1 0]
 [1 1 0 0]
 [1 1 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 0 0]
 [1 0 1 0]
 [1 0 0 1]
 [1 0 1 0]
 [1 1 0 0]
 [0 0 1 0]
 [0 0 0 0]
 [1 0 1 0]
 [1 1 0 1]
 [1 0 1 0]
 [1 1 1 1]
 [1 0 1 0]
 [1 0 1 1]
 [1 0 1 0]
 [1 0 0 0]
 [1 0 1 0]
 [1 1 0 0]
 [0 0 1 0]
 [0 1 0 0]]


In [25]:
flattened_array = result.flatten()
print(flattened_array)



[1 0 0 0 0 0 1 0 1 0 1 0 1 1 1 1 1 0 1 0 1 0 1 1 1 0 1 0 0 0 1 1 1 0 1 0 1
 1 1 1 1 1 1 0 1 1 0 0 1 1 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 1 0 1 0 0 1 1 0
 1 0 1 1 0 0 0 0 1 0 0 0 0 0 1 0 1 0 1 1 0 1 1 0 1 0 1 1 1 1 1 0 1 0 1 0 1
 1 1 0 1 0 1 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0]


In [12]:
original_string = "1000001010101111101010111010001110101111111011001110001000100000101010011010110000100000101011011010111110101011101010001010110000100100"

# Insert spaces every 4 characters
spaced_string = ' '.join([original_string[i:i+4] for i in range(0, len(original_string), 4)])

print(spaced_string)

1000 0010 1010 1111 1010 1011 1010 0011 1010 1111 1110 1100 1110 0010 0010 0000 1010 1001 1010 1100 0010 0000 1010 1101 1010 1111 1010 1011 1010 1000 1010 1100 0010 0100


In [ ]:
binary_message = "01000010 01101111 01101110 01101010 01101111 01110101 01110010 00100000 01101100 01100101 00100000 01101101 01101111 01101110 01100100 01100101 00100001"
binary_list = binary_message.split()
output_matrix = [matrix_permutation @ np.array(list(map(int, binary_str))).T for binary_str in binary_list]
output_flattened = np.concatenate(output_matrix).tolist()
print(output_flattened)


